# Generated by Django 3.0.7 on 2020-06-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='game_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='user',
            name='game',
        ),
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.ManyToManyField(to='register_user_game.Game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
