# Generated by Django 3.0.7 on 2020-06-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user_game', '0003_auto_20200620_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
