# Generated by Django 3.0.7 on 2020-06-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user_game', '0004_auto_20200620_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.ManyToManyField(to='register_user_game.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('my_games', 'my_games'), ('wish_games', 'wish_games')], max_length=30),
        ),
    ]
