# Generated by Django 3.0.7 on 2020-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user_game', '0007_auto_20200620_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=30)),
                ('environement', models.CharField(choices=[('Play-Station', 'Play-Station'), ('PC', 'PC'), ('Xbox', 'Xbox')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=30)),
                ('environement', models.CharField(choices=[('Play-Station', 'Play-Station'), ('PC', 'PC'), ('Xbox', 'Xbox')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='user',
            name='my_games',
            field=models.ManyToManyField(to='register_user_game.My_games'),
        ),
        migrations.AddField(
            model_name='user',
            name='wish_games',
            field=models.ManyToManyField(to='register_user_game.Wish_games'),
        ),
    ]
