# Generated by Django 3.0.7 on 2020-07-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user_game', '0008_auto_20200622_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_games',
            name='environement',
            field=models.CharField(blank=True, choices=[('Play-Station', 'Play-Station'), ('PC', 'PC'), ('Xbox', 'Xbox')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='my_games',
            name='game_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wish_games',
            name='environement',
            field=models.CharField(blank=True, choices=[('Play-Station', 'Play-Station'), ('PC', 'PC'), ('Xbox', 'Xbox')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wish_games',
            name='game_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
