# Generated by Django 3.0.7 on 2020-10-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_user_game', '0009_auto_20200707_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_games',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wish_games',
        ),
        migrations.AddField(
            model_name='my_games',
            name='type',
            field=models.CharField(blank=True, choices=[('my_games', 'my_games'), ('wish_games', 'wish_games')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='my_games',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_user_game.User'),
        ),
        migrations.AddField(
            model_name='wish_games',
            name='type',
            field=models.CharField(blank=True, choices=[('my_games', 'my_games'), ('wish_games', 'wish_games')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='wish_games',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_user_game.User'),
        ),
        migrations.AlterField(
            model_name='my_games',
            name='environement',
            field=models.CharField(blank=True, choices=[('Play_Station', 'Play_Station'), ('PC', 'PC'), ('Xbox', 'Xbox')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wish_games',
            name='environement',
            field=models.CharField(blank=True, choices=[('Play_Station', 'Play_Station'), ('PC', 'PC'), ('Xbox', 'Xbox')], max_length=30, null=True),
        ),
    ]
