# Generated by Django 3.0.7 on 2020-10-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user_game', '0010_auto_20201024_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_games',
            name='user',
        ),
        migrations.AddField(
            model_name='my_games',
            name='user',
            field=models.ManyToManyField(to='register_user_game.User'),
        ),
        migrations.RemoveField(
            model_name='wish_games',
            name='user',
        ),
        migrations.AddField(
            model_name='wish_games',
            name='user',
            field=models.ManyToManyField(to='register_user_game.User'),
        ),
    ]
