# Generated by Django 3.0.7 on 2020-10-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_user_game', '0012_remove_wish_games_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_games',
            name='type',
        ),
    ]
