# Generated by Django 3.0.7 on 2020-10-31 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register_user_game', '0014_auto_20201026_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_games',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wish_games',
            name='environement',
            field=models.CharField(blank=True, choices=[('Play_Station', 'Play_Station'), ('PC', 'PC'), ('Xbox', 'Xbox')], max_length=30, null=True),
        ),
    ]
